version: '3.7'
services:
  dp-postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbtgbot
      POSTGRES_PASSWORD: tgbot1
      POSTGRES_DB: ginotgbot
    networks:
      - bot-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    restart: on-failure

  py-test-bot:
    container_name: tgbotpostgres
    build: .
    command: python3.10 app.py
    environment:
      WEBAPP_PORT: 3001
    env_file:
      - .env
    restart: always
    ports:
      - "8443:3001"
    networks:
      - bot-network
    depends_on:
      - dp-postgres

networks:
  bot-network:
    driver: bridge